############################################################
# STEP 5 — Final Corpus TALL Clean
# Editorial boilerplate removal and semantic normalisation
# for TALL input corpus (Reinert Clustering)
#
# Input:  Step_5_TALL_file.csv   (delimiter ";")
# Output: Step_5_TALL_clean.csv  (delimiter ";", UTF-8)
#         Step_5_TALL_clean_QC.csv  (quality control log)
#
# Author: Antonio Sánchez Cordero
# Pipeline: M_Step 5 — Linguistically normalised corpus
############################################################

rm(list = ls())
graphics.off()

library(dplyr)
library(stringr)
library(readr)

############################################################
# S5.0 — Input / output parameters
############################################################

file_input  <- "Step_4_final_corpus_84_fullcols_TALL.csv"
file_output <- "Step_5_TALL_clean.csv"
file_qc     <- "Step_5_TALL_clean_QC.csv"

stopifnot(file.exists(file_input))
cat("Input:", file_input, "\n")

############################################################
# S5.1 — Load corpus
############################################################

df <- read_delim(file_input, delim = ";",
                 show_col_types = FALSE,
                 locale = locale(encoding = "UTF-8"))

cat("Records loaded:", nrow(df), "| Columns:", ncol(df), "\n")
stopifnot(nrow(df) > 0)

# Verify text column
if (!"text" %in% names(df)) {
  stop("Column 'text' not found in input file. ",
       "Please verify that the CSV was generated by Step 4.")
}

# Preserve original text for QC comparison
df$text_original <- df$text

############################################################
# S5.2 — Editorial boilerplate patterns
# Applied in order: most specific to most general
############################################################

boilerplate_patterns <- list(
  
  # ── Copyright and rights statements ──────────────────
  "copyright_elsevier"  = "\\(?\\s*[©c]\\s*\\)?\\s*\\d{4}\\s+elsevier\\s+ltd\\.?\\s+all\\s+rights\\s+reserved\\.?",
  "copyright_general"   = "\\(?\\s*[©c]\\s*\\)?\\s*\\d{4}\\s+[a-z][^.]{0,60}\\.?\\s+all\\s+rights\\s+reserved\\.?",
  "all_rights"          = "\\ball\\s+rights\\s+reserved\\.?",
  "copyright_symbol"    = "©\\s*\\d{4}[^.]{0,80}\\.",
  
  # ── Publisher declarations ────────────────────────────
  "published_elsevier"  = "published\\s+by\\s+elsevier\\s+[a-z\\.\\s]{0,30}\\.?",
  "published_by"        = "published\\s+by\\s+[a-z][^.]{0,60}\\.",
  "published_under"     = "published\\s+under\\s+[^.]{0,80}\\.",
  
  # ── Open access and licence statements ───────────────
  "open_access"         = "this\\s+is\\s+an\\s+open\\s+access\\s+article[^.]{0,120}\\.",
  "cc_license"          = "under\\s+the\\s+(cc\\s+by|creative\\s+commons)[^.]{0,120}\\.",
  "license_terms"       = "licensee\\s+[a-z][^.]{0,80}\\.",
  
  # ── DOIs and URLs ─────────────────────────────────────
  "doi_string"          = "\\bdoi\\s*[:/]\\s*10\\.\\S+",
  "url_http"            = "https?://[^\\s,;]+",
  "url_www"             = "www\\.[^\\s,;]+",
  
  # ── Scopus / WoS export artefacts ────────────────────
  "scopus_tag"          = "\\[\\s*(scopus|wos|isi|pubmed)\\s*\\]",
  "abstract_tag"        = "^\\s*abstract\\s*[:\\-]?\\s*",
  "author_keywords"     = "^\\s*(author\\s+)?keywords?\\s*[:\\-]?\\s*",
  
  # ── Generic academic boilerplate phrases ─────────────
  "in_this_paper"       = "\\bin\\s+this\\s+(paper|study|work|article|research)\\b[^,]{0,40},",
  "this_paper_presents" = "\\bthis\\s+(paper|study|work|article)\\s+(present|propose|introduce|describe|report)[^,]{0,60},",
  "results_show"        = "\\bresults?\\s+show\\s+that\\b",
  "it_is_found"         = "\\bit\\s+is\\s+(found|shown|demonstrated|concluded)\\s+that\\b",
  
  # ── Residual typographic artefacts ───────────────────
  "dash_start"          = "^\\s*[-–—]+\\s*",
  "bracket_empty"       = "\\[\\s*\\]|\\(\\s*\\)",
  "repeated_comma"      = ",\\s*,+",
  "repeated_space"      = "\\s{2,}"
)

############################################################
# S5.3 — Cleaning function
############################################################

clean_boilerplate <- function(x, patterns) {
  x <- as.character(x)
  x <- ifelse(is.na(x), "", x)
  
  # Initial encoding normalisation
  x <- enc2utf8(x)
  x <- iconv(x, from = "UTF-8", to = "UTF-8", sub = "")
  
  # Apply patterns in order
  for (pat in patterns) {
    x <- str_replace_all(x, regex(pat, ignore_case = TRUE), " ")
  }
  
  # Final cleanup
  x <- str_replace_all(x, "[[:cntrl:]]+", " ")
  x <- str_squish(x)
  x
}

############################################################
# S5.4 — Apply cleaning to text columns
############################################################

# Columns to clean (only those present in the dataframe)
cols_to_clean <- intersect(c("text", "AB", "TI", "DE", "ID"),
                           names(df))

cat("Columns to clean:", paste(cols_to_clean, collapse = ", "), "\n")

for (col in cols_to_clean) {
  df[[col]] <- clean_boilerplate(df[[col]], boilerplate_patterns)
  cat("  ✓", col, "cleaned\n")
}

############################################################
# S5.5 — Additional semantic normalisation
############################################################

# Restore technical acronyms in uppercase after lowercasing
acronyms <- c(
  "iaq", "hvac", "co2", "pm2\\.5", "pm10",
  "voc", "tvoc", "mvhr", "nv", "dcv",
  "bems", "ems", "ep", "cfd", "ml", "ai",
  "ashrae", "iso", "une",
  "pmv", "ppd", "ach"
)

for (a in acronyms) {
  df$text <- str_replace_all(
    df$text,
    regex(paste0("\\b", a, "\\b"), ignore_case = TRUE),
    toupper(str_replace_all(a, "\\\\.", "."))
  )
}

# CO₂ → CO2 for consistent tokenisation
df$text <- str_replace_all(
  df$text,
  regex("co₂|co2", ignore_case = TRUE),
  "CO2"
)

# Normalise separators: semicolon → comma
df$text <- str_replace_all(df$text, ";", ",")
df$text <- str_squish(df$text)

cat("Semantic normalisation completed\n")

############################################################
# S5.6 — Post-cleaning quality control
############################################################

# Residual boilerplate terms for verification
boilerplate_check <- c(
  "elsevier", "all rights reserved", "ltd\\.",
  "published by", "open access", "creative commons",
  "doi:", "https?://", "www\\."
)

qc_results <- data.frame(
  pattern     = boilerplate_check,
  n_docs_with = sapply(boilerplate_check, function(p) {
    sum(str_detect(df$text, regex(p, ignore_case = TRUE)),
        na.rm = TRUE)
  }),
  stringsAsFactors = FALSE
)

cat("\n--- Quality control ---\n")
print(qc_results)

# Documents with empty or very short text after cleaning
n_empty <- sum(nchar(df$text) < 50, na.rm = TRUE)
cat("Documents with text < 50 characters after cleaning:",
    n_empty, "\n")

if (n_empty > 0) {
  warning("There are ", n_empty,
          " documents with very short text. Manual review recommended.")
  short_docs <- df %>%
    filter(nchar(text) < 50) %>%
    select(any_of(c("UT", "DI", "TI", "text")))
  cat("Affected documents:\n")
  print(short_docs)
}

# Mean text length before and after
cat("Mean text length ORIGINAL:",
    round(mean(nchar(df$text_original), na.rm = TRUE)), "chars\n")
cat("Mean text length CLEAN:   ",
    round(mean(nchar(df$text),          na.rm = TRUE)), "chars\n")

############################################################
# S5.7 — Export clean CSV for TALL
############################################################

# Remove auxiliary QC column before export
df_export <- df %>% select(-text_original)

write_delim(df_export, file_output,
            delim = ";", na = "", quote = "needed")
cat("\n[Saved]", file_output, "—",
    nrow(df_export), "records,",
    ncol(df_export), "columns\n")

# Integrity check on exported CSV
test <- read_delim(file_output, delim = ";",
                   show_col_types = FALSE)
stopifnot("text" %in% names(test))
stopifnot(nrow(test) == nrow(df))
cat("✓ CSV integrity verified\n")

############################################################
# S5.8 — Export QC log
############################################################

# Comparative log before/after by document
qc_log <- df %>%
  select(any_of(c("UT", "DI", "TI"))) %>%
  mutate(
    chars_original      = nchar(df$text_original),
    chars_clean         = nchar(df$text),
    reduction_pct       = round(
      (chars_original - nchar(df$text)) / chars_original * 100, 1),
    boilerplate_residual = str_detect(
      df$text,
      regex("elsevier|all rights reserved|ltd\\.",
            ignore_case = TRUE))
  )

write.csv(qc_log, file_qc, row.names = FALSE)
cat("[Saved]", file_qc, "— quality control log\n")

############################################################
# S5.9 — Final summary
############################################################

cat("\n========== STEP 5 SUMMARY ==========\n")
cat("Input:            ", file_input,  "\n")
cat("Output TALL:      ", file_output, "\n")
cat("Output QC log:    ", file_qc,     "\n")
cat("Records:          ", nrow(df_export), "\n")
cat("Columns:          ", ncol(df_export), "\n")
cat("Residual boilerplate (elsevier/ltd):",
    sum(str_detect(df_export$text,
                   regex("elsevier|ltd\\.",
                         ignore_case = TRUE)),
        na.rm = TRUE), "docs\n")
cat("=====================================\n")
cat("\nImport into TALL: ", file_output,
    " | Text column: 'text'\n")
tall()
